"""
Core orchestration module for the TemiAgent Embodied AI Framework.

This module integrates the VisionServer, MqttBridge, and a local Vision-Language Model
(via LMStudio/OpenAI API) to create an autonomous cognitive loop. It handles the
time-series manifold alignment by requesting asymmetric frames and parses the VLM's
JSON output via a dedicated SkillRouter to execute physical commands safely.
"""

import time
import cv2
import os
import logging
import json
import base64
import re
from openai import OpenAI
from vision_server import VisionServer
from mqtt_bridge import MqttBridge

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(message)s')

DEBUG_FRAMES_DIR = "debug_frames"
SKILLS_PROMPT_FILE = "Skills.md"


class SkillRouter:
    """
    Parses and routes the LLM's JSON output to the corresponding physical actions.
    
    This acts as a strict execution firewall, ensuring that the AI can only trigger
    pre-defined actions (speak, navigate) and never executes arbitrary raw code.
    """

    def __init__(self, mqtt_bridge: MqttBridge):
        """
        Initialize the SkillRouter with an active MQTT bridge.

        Args:
            mqtt_bridge (MqttBridge): The active connection to the robot's MQTT topics.
        """
        self.mqtt = mqtt_bridge

    def route(self, llm_response: str) -> None:
        """
        Parse the JSON array from the LLM response and execute the corresponding MQTT actions.

        This method actively filters out Chain of Thought (`<think>`) reasoning blocks
        and markdown formatting to reliably extract the pure JSON Schema.

        Args:
            llm_response (str): The raw text response generated by the Vision-Language Model.
        """
        logging.info("SkillRouter: Parsing LLM response...")
        
        # Extract JSON array using regex to ignore `<think>` blocks and markdown
        json_match = re.search(r'\[\s*\{.*?\}\s*\]', llm_response, re.DOTALL)
        if not json_match:
            # Fallback parsing if regex misses
            parts = llm_response.split("</think>")
            json_str = parts[-1].strip() if len(parts) > 1 else llm_response.strip()
            if json_str.startswith("```json"):
                json_str = json_str[7:]
            if json_str.endswith("```"):
                json_str = json_str[:-3]
        else:
            json_str = json_match.group(0)

        try:
            actions = json.loads(json_str.strip())
            if not isinstance(actions, list):
                logging.error("SkillRouter: Expected JSON array of actions.")
                return

            for action_obj in actions:
                action_name = action_obj.get("action")
                params = action_obj.get("parameters", {})
                
                logging.info(f"SkillRouter: Executing action '{action_name}' with params {params}")
                
                if action_name == "speak":
                    text = params.get("text", "")
                    continue_listening = params.get("continue_listening", False)
                    self.mqtt.publish_speak(text, continue_listening=continue_listening)
                    
                elif action_name == "navigate":
                    target = params.get("target_location", "")
                    self.mqtt.publish_navigate(target)
                    
                else:
                    logging.warning(f"SkillRouter: Unknown action '{action_name}'")
                    
        except json.JSONDecodeError as e:
            logging.error(f"SkillRouter: Failed to parse JSON. Error: {e}")
            logging.debug(f"Raw string attempted to parse: {json_str}")


class AgentCore:
    """
    Main orchestrator for the TemiAgent system.
    
    Manages the lifecycle of the WebSocket VisionServer, the MQTT event bridge,
    and the API connections to the local LLM.
    """

    def __init__(self):
        """Initialize all neural and sensory pathways for the agent."""
        self.vision = VisionServer()
        self.mqtt = MqttBridge()
        self.mqtt.set_asr_callback(self.on_asr_event)
        self.router = SkillRouter(self.mqtt)
        
        # Initialize LMStudio OpenAI Client
        self.lm_client = OpenAI(base_url="http://localhost:1234/v1", api_key="lm-studio")
        
        if not os.path.exists(DEBUG_FRAMES_DIR):
            os.makedirs(DEBUG_FRAMES_DIR)
            
        # Load System Prompt
        self.system_prompt = "You are Temi, an Embodied AI."
        if os.path.exists(SKILLS_PROMPT_FILE):
            with open(SKILLS_PROMPT_FILE, "r", encoding="utf-8") as f:
                self.system_prompt = f.read()

    def image_to_base64(self, frame) -> str:
        """
        Encode an OpenCV BGR frame into a Base64 string for OpenAI's Vision API.

        Args:
            frame (np.ndarray): The OpenCV image to encode.

        Returns:
            str: The Base64 encoded JPEG string.
        """
        _, buffer = cv2.imencode('.jpg', frame)
        return base64.b64encode(buffer).decode('utf-8')

    def on_asr_event(self, payload: dict) -> None:
        """
        Handle incoming Automatic Speech Recognition (ASR) events from the robot.

        Triggers the Asymmetric Backward Sampling process to retrieve keyframes from
        the VisionBuffer and dispatches the multi-modal request to the VLM.

        Args:
            payload (dict): The parsed JSON payload containing 'text' and 'timestamp_ms'.
        """
        text = payload.get("text", "")
        timestamp_ms = payload.get("timestamp_ms", 0)
        
        logging.info(f"AgentCore: Received ASR '{text}' at T={timestamp_ms}")
        
        # Extract 3 asymmetric keyframes: T-1000, T-500, T
        keyframes = self.vision.buffer.get_keyframes(timestamp_ms)
        
        if not keyframes:
            logging.warning("AgentCore: No frames found in VisionBuffer!")
            self.mqtt.publish_speak("我的視覺神經沒有畫面", continue_listening=False)
            return
            
        base64_images = []
        for i, kf in enumerate(keyframes):
            frame = kf["frame"]
            base64_images.append(self.image_to_base64(frame))
            
            # Save for debug
            filename_suffix = "T-1000" if i == 0 else "T-500" if i == 1 else "T"
            filename = os.path.join(DEBUG_FRAMES_DIR, f"asr_{timestamp_ms}_{filename_suffix}.jpg")
            cv2.imwrite(filename, frame)
            
        # Call VLM
        self.call_vlm(text, base64_images)

    def call_vlm(self, user_text: str, base64_images: list) -> None:
        """
        Construct and send a multi-modal context request to the VLM.

        Args:
            user_text (str): The recognized user speech text.
            base64_images (list): A list of three Base64 encoded chronological images.
        """
        logging.info("AgentCore: Sending context to VLM (LMStudio)...")
        
        content = [{"type": "text", "text": f"User said: {user_text}\nHere are the 3 consecutive frames (T-1000ms, T-500ms, T) leading up to the end of speech:"}]
        for b64 in base64_images:
            content.append({
                "type": "image_url",
                "image_url": {
                    "url": f"data:image/jpeg;base64,{b64}"
                }
            })
            
        messages = [
            {"role": "system", "content": self.system_prompt},
            {"role": "user", "content": content}
        ]
        
        try:
            response = self.lm_client.chat.completions.create(
                model="local-model", # Usually ignored by LMStudio
                messages=messages,
                temperature=0.3,
                max_tokens=500
            )
            
            llm_response = response.choices[0].message.content
            logging.info(f"AgentCore: VLM Response:\n{llm_response}")
            
            # Route to execution
            self.router.route(llm_response)
            
        except Exception as e:
            logging.error(f"AgentCore: Failed to call VLM. Error: {e}")
            self.mqtt.publish_speak("大腦連線發生錯誤", continue_listening=False)

    def run(self) -> None:
        """
        Start the Agent Core event loop.
        
        This boots the background WebSocket VisionServer and the MQTT event bridge.
        """
        self.vision.run_in_background()
        self.mqtt.start()
        logging.info("AgentCore is running. Press Ctrl+C to stop.")
        
        try:
            while True:
                time.sleep(1)
        except KeyboardInterrupt:
            logging.info("AgentCore stopping...")
            self.mqtt.stop()

if __name__ == "__main__":
    core = AgentCore()
    core.run()
