#!/usr/bin/env python3
"""Evaluate live Hermes action selection with canonical mock ASR events.

Offline evaluation is the default. Use --live for MQTT evaluation, or --offline to inspect and validate the
case catalogue without connecting to MQTT or publishing robot commands. This
is an evaluation runner, not a deterministic unit test: model output can vary.
"""

from __future__ import annotations

import argparse
from dataclasses import asdict, dataclass
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import sys
import tempfile
import threading
import time
from typing import Any
import uuid

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
from create_mock_event_images import build_event  # noqa: E402

EVIDENCE_README = """# Action-selection evidence

Generated by /TemiAgent/tools/test_action_selection_cases.py.

Each <run_id>/memory-backup/<event_id>/ directory contains the pre-cleanup
memory indexes, any exact event-owned abnormal artifact, and a SHA-256
manifest. These are rollback/debug artifacts, not production memory.
"""


@dataclass(frozen=True)
class ActionSelectionCase:
    """One utterance used to evaluate response/action consistency."""
    case_id: str
    text: str
    category: str
    purpose: str


CASES = (
    ActionSelectionCase("BP-01", "幫我記錄血壓，收縮壓117，舒張壓73，心跳76", "blood_pressure_complete_normal", "完整且一般範圍的非整數邊界讀值；確認後不應強制追問"),
    ActionSelectionCase("BP-02", "幫我記錄血壓127/76，心跳84", "blood_pressure_compact_complete", "完整簡寫與不規則數值；確認後不應強制追問"),
    ActionSelectionCase("BP-03", "幫我記錄舒張壓93，心跳87", "blood_pressure_missing_systolic_high", "舒張壓偏高且缺少收縮壓，必須追問"),
    ActionSelectionCase("BP-04", "幫我記錄收縮壓151，舒張壓96，心跳88", "blood_pressure_high", "完整但明顯偏高的讀值應追問目前症狀"),
    ActionSelectionCase("BP-05", "幫我記錄收縮壓133，心跳82", "blood_pressure_missing_diastolic", "缺少舒張壓，必須要求補充資訊"),
    ActionSelectionCase("BP-06", "幫我記錄舒張壓86，脈搏89", "blood_pressure_missing_systolic", "缺少收縮壓，必須要求補充資訊"),
    ActionSelectionCase("BP-07", "幫我記錄血壓", "blood_pressure_missing_values", "沒有任何量測值，不得假裝已記錄"),
    ActionSelectionCase("BP-08", "幫我記錄影壓舒張壓93，心跳91", "blood_pressure_asr_typo", "涵蓋血壓被 ASR 誤辨為影壓及缺少收縮壓"),
    ActionSelectionCase("BP-09", "幫我記錄血壓，收縮壓一百一十七，舒張壓七十三，心跳七十六", "blood_pressure_chinese_numbers_normal", "完整中文數字的一般範圍讀值"),
    ActionSelectionCase("BP-10", "幫我記錄血壓129，心跳81", "blood_pressure_ambiguous_value", "單一血壓數值無法判斷是收縮壓或舒張壓"),
    ActionSelectionCase("BP-11", "我血壓很高，心跳也很快", "blood_pressure_subjective_no_values", "只有主觀描述，不能假裝已記錄數值"),
    ActionSelectionCase("BP-12", "幫我記錄血壓，收縮壓abc，舒張壓77，心跳83", "blood_pressure_invalid_systolic", "收縮壓不是有效數值，必須澄清"),
    ActionSelectionCase("BP-13", "收縮壓183，舒張壓116，心跳104", "blood_pressure_severely_high", "嚴重偏高讀值應進入安全追問"),
    ActionSelectionCase("BP-14", "血壓是108/68，心跳54", "heart_rate_low", "完整血壓但心跳偏低，應確認身體狀況"),
    ActionSelectionCase("BP-15", "血壓是116/74，心跳107", "heart_rate_high", "完整血壓但心跳偏快，應確認身體狀況"),
    ActionSelectionCase("BP-16", "血壓是124/76", "heart_rate_omitted", "現行血壓契約不要求心跳；不驗證心跳是否保存"),
    ActionSelectionCase("BP-17", "心跳是78", "heart_rate_only", "只有心跳，不足以完成血壓紀錄"),
    ActionSelectionCase("BP-18", "幫我記錄血壓，收縮壓118，書張壓75，心跳79", "diastolic_asr_typo", "涵蓋舒張壓被 ASR 誤辨為書張壓"),
    ActionSelectionCase("BP-19", "血壓是15一/九6，心跳八七", "mixed_invalid_numbers", "數字混合辨識錯誤時不得猜測並寫入"),
    ActionSelectionCase("BP-20", "血壓是86/57，心跳96，我有點頭暈", "low_blood_pressure_with_symptom", "偏低讀值伴隨頭暈，必須進入安全追問"),
    ActionSelectionCase("SYM-01", "我的頭不太舒服", "discomfort_ambiguous", "模糊頭部不適需要釐清症狀與安全狀況"),
    ActionSelectionCase("SYM-02", "我頭痛", "headache", "頭痛但程度與伴隨症狀未知"),
    ActionSelectionCase("SYM-03", "我又不舒服了", "repeated_discomfort", "重複且模糊的不適應要求後續回答"),
)


class EvaluationFailure(RuntimeError):
    """A live case could not produce usable canonical command evidence."""


def ensure_evidence_readme(evidence_root: Path) -> Path:
    """Create or refresh the README owned by this evidence runner."""
    evidence_root.mkdir(parents=True, exist_ok=True)
    readme = evidence_root / "README.md"
    if readme.exists():
        existing = readme.read_text(encoding="utf-8")
        owner_marker = "Generated by /TemiAgent/tools/test_action_selection_cases.py."
        if owner_marker not in existing:
            raise EvaluationFailure(f"refusing to replace unowned evidence README: {readme}")
        if existing != EVIDENCE_README:
            _atomic_write(readme, EVIDENCE_README.encode("utf-8"))
    else:
        with readme.open("x", encoding="utf-8", newline="\n") as handle:
            handle.write(EVIDENCE_README)
    return readme


def _atomic_write(path: Path, data: bytes) -> None:
    """Replace one file atomically while retaining its existing mode."""
    mode = path.stat().st_mode & 0o777
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary_path, mode)
        os.replace(temporary_path, path)
    finally:
        temporary_path.unlink(missing_ok=True)


def cleanup_owned_memory(*, memory_root: Path, event_id: str, run_id: str, backup_root: Path) -> dict[str, Any]:
    """Remove one runner-owned event from the two known memory indexes.

    Refuse cleanup when ownership, parsing, uniqueness, or side-effect scope is
    uncertain. The caller receives evidence instead of an unbounded deletion.
    """
    expected_prefix = f"evt_action_eval_{run_id}_"
    if not event_id.startswith(expected_prefix):
        raise EvaluationFailure("cleanup refused: event ID is not owned by this runner invocation")

    event_log = memory_root / "event_log.jsonl"
    daily_state = memory_root / "daily_state.json"
    abnormal_artifact = memory_root / "abnormal_events" / f"{event_id}.json"
    if not event_log.exists():
        return {"status": "NO_MEMORY_WRITE", "event_id": event_id, "removed_event_count": 0}

    original_event_bytes = event_log.read_bytes()
    original_daily_bytes = daily_state.read_bytes() if daily_state.exists() else None
    parsed_lines: list[tuple[bytes, dict[str, Any] | None]] = []
    for line_number, raw_line in enumerate(original_event_bytes.splitlines(keepends=True), start=1):
        if not raw_line.strip():
            parsed_lines.append((raw_line, None))
            continue
        try:
            item = json.loads(raw_line.decode("utf-8"))
        except (UnicodeDecodeError, json.JSONDecodeError) as exc:
            raise EvaluationFailure(f"cleanup refused: invalid event_log.jsonl line {line_number}") from exc
        if not isinstance(item, dict):
            raise EvaluationFailure(f"cleanup refused: non-object event_log.jsonl line {line_number}")
        parsed_lines.append((raw_line, item))

    matches = [item for _, item in parsed_lines if item is not None and item.get("event_id") == event_id]
    if not matches:
        return {"status": "NO_MEMORY_WRITE", "event_id": event_id, "removed_event_count": 0}
    if len(matches) != 1:
        raise EvaluationFailure(f"cleanup refused: expected one event record, found {len(matches)}")

    abnormal_bytes: bytes | None = None
    if abnormal_artifact.exists():
        abnormal_bytes = abnormal_artifact.read_bytes()
        try:
            abnormal_payload = json.loads(abnormal_bytes.decode("utf-8"))
        except (UnicodeDecodeError, json.JSONDecodeError) as exc:
            raise EvaluationFailure("cleanup refused: invalid owned abnormal artifact") from exc
        if not isinstance(abnormal_payload, dict) or abnormal_payload.get("event_id") != event_id:
            raise EvaluationFailure("cleanup refused: abnormal artifact ownership mismatch")

    other_references: list[str] = []
    event_token = event_id.encode("utf-8")
    for path in memory_root.rglob("*"):
        if not path.is_file() or path in {event_log, daily_state, abnormal_artifact}:
            continue
        try:
            if event_token in path.read_bytes():
                other_references.append(path.relative_to(memory_root).as_posix())
        except OSError as exc:
            raise EvaluationFailure(f"cleanup refused: cannot inspect {path}") from exc
    if other_references:
        raise EvaluationFailure(
            "cleanup refused: event has additional memory artifacts: " + ", ".join(sorted(other_references))
        )

    daily: dict[str, Any] | None = None
    if original_daily_bytes is not None:
        try:
            parsed_daily = json.loads(original_daily_bytes.decode("utf-8"))
        except json.JSONDecodeError as exc:
            raise EvaluationFailure("cleanup refused: invalid daily_state.json") from exc
        if not isinstance(parsed_daily, dict):
            raise EvaluationFailure("cleanup refused: daily_state.json is not an object")
        daily = parsed_daily
        recent_ids = daily.get("recent_event_ids", [])
        if not isinstance(recent_ids, list) or not all(isinstance(item, str) for item in recent_ids):
            raise EvaluationFailure("cleanup refused: recent_event_ids is not a string list")
        if recent_ids.count(event_id) > 1:
            raise EvaluationFailure("cleanup refused: duplicate event ID in daily_state.json")
        daily["recent_event_ids"] = [item for item in recent_ids if item != event_id]

    new_event_bytes = b"".join(
        raw_line
        for raw_line, item in parsed_lines
        if item is None or item.get("event_id") != event_id
    )
    new_daily_bytes = (
        (json.dumps(daily, ensure_ascii=False, indent=2) + "\n").encode("utf-8")
        if daily is not None
        else None
    )

    case_backup = backup_root / event_id
    case_backup.mkdir(parents=True, exist_ok=False)
    shutil.copy2(event_log, case_backup / "event_log.jsonl")
    if daily_state.exists():
        shutil.copy2(daily_state, case_backup / "daily_state.json")
    if abnormal_artifact.exists():
        artifact_backup = case_backup / "abnormal_events" / abnormal_artifact.name
        artifact_backup.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(abnormal_artifact, artifact_backup)
    manifest = {
        "event_id": event_id,
        "event_log_sha256": hashlib.sha256(original_event_bytes).hexdigest(),
        "daily_state_sha256": (
            hashlib.sha256(original_daily_bytes).hexdigest() if original_daily_bytes is not None else None
        ),
        "abnormal_artifact_sha256": (
            hashlib.sha256(abnormal_bytes).hexdigest() if abnormal_bytes is not None else None
        ),
    }
    (case_backup / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    if event_log.read_bytes() != original_event_bytes:
        raise EvaluationFailure("cleanup refused: event_log.jsonl changed concurrently")
    if original_daily_bytes is not None and daily_state.read_bytes() != original_daily_bytes:
        raise EvaluationFailure("cleanup refused: daily_state.json changed concurrently")
    if abnormal_bytes is not None and abnormal_artifact.read_bytes() != abnormal_bytes:
        raise EvaluationFailure("cleanup refused: abnormal artifact changed concurrently")

    try:
        _atomic_write(event_log, new_event_bytes)
        if new_daily_bytes is not None:
            _atomic_write(daily_state, new_daily_bytes)
        if abnormal_bytes is not None:
            abnormal_artifact.unlink()
    except Exception as exc:
        _atomic_write(event_log, original_event_bytes)
        if original_daily_bytes is not None:
            _atomic_write(daily_state, original_daily_bytes)
        raise EvaluationFailure("cleanup failed; original memory files were restored") from exc

    if event_token in event_log.read_bytes():
        raise EvaluationFailure("cleanup verification failed: event remains in event_log.jsonl")
    if daily_state.exists():
        verified_daily = json.loads(daily_state.read_text(encoding="utf-8"))
        if event_id in verified_daily.get("recent_event_ids", []):
            raise EvaluationFailure("cleanup verification failed: event remains in daily_state.json")
    if abnormal_artifact.exists():
        raise EvaluationFailure("cleanup verification failed: abnormal artifact remains")
    return {
        "status": "CLEANED",
        "event_id": event_id,
        "removed_event_count": 1,
        "removed_artifact_count": 1 if abnormal_bytes is not None else 0,
        "backup_dir": case_backup.as_posix(),
    }


class CommandCapture:
    """Subscribe before publication and retain canonical command requests."""
    def __init__(self, host: str, port: int, robot_id: str) -> None:
        try:
            import paho.mqtt.client as mqtt
        except ImportError as exc:
            raise EvaluationFailure("paho-mqtt is required for live mode; run with the hermes-temi-bridge environment") from exc
        self._mqtt = mqtt
        self.host = host
        self.port = port
        self.robot_id = robot_id
        self.ready = threading.Event()
        self.messages: list[dict[str, Any]] = []
        self.client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2, client_id=f"action-selection-{uuid.uuid4().hex[:12]}")
        self.client.on_connect = self._on_connect
        self.client.on_message = self._on_message

    def _on_connect(self, client: Any, _userdata: Any, _flags: Any, reason_code: Any, _properties: Any) -> None:
        if not bool(getattr(reason_code, "is_failure", reason_code != 0)):
            client.subscribe(f"temi/{self.robot_id}/cmd/request", qos=1)
            self.ready.set()

    def _on_message(self, _client: Any, _userdata: Any, message: Any) -> None:
        try:
            payload = json.loads(message.payload.decode("utf-8"))
        except (UnicodeDecodeError, json.JSONDecodeError):
            return
        if isinstance(payload, dict):
            self.messages.append(payload)

    def start(self) -> None:
        self.client.connect(self.host, self.port, keepalive=30)
        self.client.loop_start()
        if not self.ready.wait(10):
            self.stop()
            raise EvaluationFailure("MQTT observer did not connect and subscribe within 10 seconds")

    def stop(self) -> None:
        self.client.loop_stop()
        self.client.disconnect()

    def publish(self, payload: dict[str, Any]) -> None:
        topic = f"temi/{self.robot_id}/asr/final"
        info = self.client.publish(topic, json.dumps(payload, ensure_ascii=False), qos=1)
        info.wait_for_publish(timeout=10)
        if info.rc != self._mqtt.MQTT_ERR_SUCCESS:
            raise EvaluationFailure(f"MQTT publish failed with rc={info.rc}")

    def wait_for_event(self, event_id: str, timeout: float) -> dict[str, Any]:
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            for payload in list(self.messages):
                if payload.get("event_id") == event_id:
                    return payload
            time.sleep(0.05)
        raise EvaluationFailure(f"timed out waiting for cmd/request event_id={event_id}")


def select_cases(case_ids: list[str]) -> tuple[ActionSelectionCase, ...]:
    """Return all cases, or a caller-selected subset in catalogue order."""
    if not case_ids:
        return CASES
    requested = set(case_ids)
    known = {case.case_id for case in CASES}
    unknown = sorted(requested - known)
    if unknown:
        raise ValueError(f"unknown case id(s): {', '.join(unknown)}")
    return tuple(case for case in CASES if case.case_id in requested)


def extract_action_types(command: dict[str, Any]) -> list[str]:
    """Extract valid action type strings from a canonical command request."""
    actions = command.get("actions")
    if not isinstance(actions, list):
        return []
    return [item["type"] for item in actions if isinstance(item, dict) and isinstance(item.get("type"), str)]


_REPLY_PATTERN = re.compile(
    r"(請問|是否|有沒有|哪裡|哪一|多少|什麼|怎麼|為什麼|能否|可以嗎|好嗎|嗎[？?]?$|呢[？?]?$)"
)


def response_requires_reply(text: str) -> bool:
    """Return whether response text directly asks the user to answer."""
    normalized = text.strip()
    return "?" in normalized or "？" in normalized or bool(_REPLY_PATTERN.search(normalized))


def evaluate_response_action_consistency(command: dict[str, Any]) -> tuple[bool, list[str]]:
    """Compare speak/ask_clarification types with their actual response text."""
    actions = command.get("actions")
    if not isinstance(actions, list):
        return False, []
    expected: list[str] = []
    consistent = True
    for action in actions:
        if not isinstance(action, dict) or action.get("type") not in {"speak", "ask_clarification"}:
            continue
        text = action.get("text")
        if not isinstance(text, str) or not text.strip():
            consistent = False
            continue
        expected_type = "ask_clarification" if response_requires_reply(text) else "speak"
        expected.append(expected_type)
        if action["type"] != expected_type:
            consistent = False
    return consistent and bool(expected), expected


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Evaluate action selection for blood-pressure and discomfort utterances.")
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument("--offline", action="store_true", help="Validate/list cases without MQTT or model inference (default).")
    modes.add_argument("--live", action="store_true", help="Publish ASR events via MQTT; may cause Temi speech and memory writes.")
    parser.add_argument("--list", action="store_true", help="Print the selected case catalogue and exit.")
    parser.add_argument("--case", action="append", default=[], metavar="ID", help="Run one case ID; repeat to select several.")
    parser.add_argument("--broker", default="localhost")
    parser.add_argument("--port", type=int, default=1883)
    parser.add_argument("--robot-id", default="temi-01")
    parser.add_argument("--shared-root", type=Path, default=ROOT / "temi_shared")
    parser.add_argument("--bridge-root", default="/TemiAgent/temi_shared")
    parser.add_argument("--timeout", type=float, default=90.0, help="Seconds to wait for each cmd/request.")
    parser.add_argument("--delay", type=float, default=1.0, help="Seconds between live cases.")
    parser.add_argument(
        "--cleanup-memory-after-case",
        action="store_true",
        help="Back up and remove this run's exact event from known memory artifacts after each live case.",
    )
    parser.add_argument("--memory-root", type=Path, default=ROOT / "memory")
    parser.add_argument(
        "--evidence-root",
        type=Path,
        default=ROOT / "logs" / "action_selection",
        help="Parent directory for cleanup backups.",
    )
    parser.add_argument("--json", action="store_true", help="Emit a machine-readable summary.")
    return parser


def offline_summary(cases: tuple[ActionSelectionCase, ...]) -> dict[str, Any]:
    """Validate catalogue invariants without writing files or contacting MQTT."""
    ids = [case.case_id for case in cases]
    if len(ids) != len(set(ids)):
        raise EvaluationFailure("case IDs must be unique")
    invalid = [case.case_id for case in cases if not case.text.strip()]
    if invalid:
        raise EvaluationFailure(f"invalid case definitions: {', '.join(invalid)}")
    return {
        "mode": "offline",
        "catalogue_status": "READY",
        "case_count": len(cases),
        "cases": [asdict(case) for case in cases],
        "limitations": [
            "No MQTT publication, Resident invocation, LM Studio inference, command execution, or memory assertion occurred.",
            "The catalogue does not assert scenario-level correctness; live evaluation only checks response/action consistency.",
            "Heart-rate values may appear in utterances, but persistence is a known contract gap and is not an acceptance condition.",
        ],
    }


def run_live(args: argparse.Namespace, cases: tuple[ActionSelectionCase, ...]) -> dict[str, Any]:
    """Publish each case and compare the matching command action type."""
    run_id = f"{int(time.time())}_{uuid.uuid4().hex[:6]}"
    if args.cleanup_memory_after_case:
        ensure_evidence_readme(args.evidence_root)
    capture = CommandCapture(args.broker, args.port, args.robot_id)
    results: list[dict[str, Any]] = []
    capture.start()
    stopped_after_cleanup_refusal = False
    try:
        for index, case in enumerate(cases):
            event_id = f"evt_action_eval_{run_id}_{case.case_id.lower().replace('-', '_')}"
            payload = build_event(
                shared_root=args.shared_root,
                bridge_root=args.bridge_root,
                robot_id=args.robot_id,
                event_id=event_id,
                conversation_id=f"conv_action_eval_{run_id}_{case.case_id.lower()}",
                text=case.text,
                language="zh-TW",
                timestamp_ms=int(time.time() * 1000),
            )
            capture.publish(payload)
            try:
                command = capture.wait_for_event(event_id, args.timeout)
                actual_actions = extract_action_types(command)
                consistent, expected_actions = evaluate_response_action_consistency(command)
                case_payload = asdict(case)
                results.append({
                    **case_payload,
                    "event_id": event_id,
                    "expected_actions_from_response": expected_actions,
                    "actual_actions": actual_actions,
                    "response_texts": [
                        action.get("text") for action in command.get("actions", [])
                        if isinstance(action, dict) and isinstance(action.get("text"), str)
                    ],
                    "response_action_consistency": "CONSISTENT" if consistent else "INCONSISTENT",
                })
            except EvaluationFailure as exc:
                case_payload = asdict(case)
                results.append({
                    **case_payload,
                    "event_id": event_id,
                    "expected_actions_from_response": [],
                    "actual_actions": [],
                    "response_action_consistency": "NOT_EVALUATED",
                    "error": str(exc),
                })
            if args.cleanup_memory_after_case:
                try:
                    cleanup = cleanup_owned_memory(
                        memory_root=args.memory_root,
                        event_id=event_id,
                        run_id=run_id,
                        backup_root=args.evidence_root / run_id / "memory-backup",
                    )
                except EvaluationFailure as exc:
                    cleanup = {"status": "CLEANUP_REFUSED", "event_id": event_id, "error": str(exc)}
                    results[-1]["run_error"] = "memory cleanup refused"
                results[-1]["memory_cleanup"] = cleanup
                if cleanup["status"] == "CLEANUP_REFUSED":
                    stopped_after_cleanup_refusal = True
                    break
            if index + 1 < len(cases) and args.delay > 0:
                time.sleep(args.delay)
    finally:
        capture.stop()
    consistency_passed = (
        len(results) == len(cases)
        and all(item["response_action_consistency"] == "CONSISTENT" for item in results)
    )
    run_passed = consistency_passed and not stopped_after_cleanup_refusal
    return {
        "mode": "live",
        "run_status": "PASS" if run_passed else "FAIL",
        "response_action_consistency_status": "PASS" if consistency_passed else "FAIL",
        "run_id": run_id,
        "broker": args.broker,
        "port": args.port,
        "robot_id": args.robot_id,
        "planned_case_count": len(cases),
        "case_count": len(results),
        "stopped_after_cleanup_refusal": stopped_after_cleanup_refusal,
        "results": results,
        "limitations": [
            "Live model output can be nondeterministic; one pass is evidence, not a stability guarantee.",
            "A connected Android client may execute every published cmd/request.",
            "Heart-rate values may appear in utterances, but persistence is a known contract gap and is not asserted.",
            "Response/action consistency does not assert scenario-level correctness, medical interpretation, or successful memory persistence.",
        ],
    }


def print_human(summary: dict[str, Any]) -> None:
    if summary["mode"] == "offline":
        print(f"OFFLINE_CASES_READY case_count={summary['case_count']}")
        for case in summary["cases"]:
            print(f"{case['case_id']} text={case['text']}")
        return
    for result in summary["results"]:
        actual = ",".join(result["actual_actions"]) or "NONE"
        expected = ",".join(result["expected_actions_from_response"]) or "NONE"
        print(f"{result['response_action_consistency']}[{result['case_id']}]: expected_from_response={expected} actual={actual}")
        for response_text in result.get("response_texts", []):
            print(f"  response={response_text}")
        if result.get("error"):
            print(f"  error={result['error']}")
        if result.get("memory_cleanup"):
            cleanup = result["memory_cleanup"]
            print(f"  memory_cleanup={cleanup['status']}")
            if cleanup.get("backup_dir"):
                print(f"  memory_backup={cleanup['backup_dir']}")
            if cleanup.get("error"):
                print(f"  cleanup_error={cleanup['error']}")
    print(
        f"RESPONSE_ACTION_CONSISTENCY_{summary['response_action_consistency_status']} "
        f"run_status={summary['run_status']} run_id={summary['run_id']}"
    )


def main() -> int:
    args = build_parser().parse_args()
    try:
        cases = select_cases(args.case)
    except ValueError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    if args.list or not args.live:
        summary = offline_summary(cases)
    else:
        print(
            f"LIVE MODE: publishing {len(cases)} ASR events to temi/{args.robot_id}/asr/final via "
            f"{args.broker}:{args.port}. A connected Temi may speak and runtime memory may change.",
            file=sys.stderr,
        )
        try:
            summary = run_live(args, cases)
        except (EvaluationFailure, OSError) as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 2
    if args.json:
        print(json.dumps(summary, ensure_ascii=False, indent=2))
    else:
        print_human(summary)
    if summary["mode"] == "offline":
        return 0 if summary["catalogue_status"] == "READY" else 1
    return 0 if summary["run_status"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
